service: serverlesswp-wordpress-starter

provider:
  name: aws
  runtime: nodejs22.x
  httpApi:
    payload: '2.0'

functions:
  requestHandler:
    handler: api/index.handler
    memorySize: 1024
    timeout: 15
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      #DATABASE: 'btnrdn8y6zrowvjt8uam'
      #USERNAME: 'ux4ngsnn2eem1it4'
      #PASSWORD: Kf88Vjldb1V4A9l7JlzL
      #HOST: 'btnrdn8y6zrowvjt8uam-mysql.services.clever-cloud.com'